# Generated by Django 5.1 on 2024-11-01 10:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Назва')),
                ('division', models.SmallIntegerField(choices=[(1, '1садн'), (2, '2садн'), (3, '1адн'), (4, '2адн'), (5, 'реабатр')], default=1, verbose_name='Підрозділ')),
                ('battery', models.SmallIntegerField(choices=[(1, '1сабатр'), (2, '2сабатр'), (3, '3сабатп'), (4, '1абатр'), (5, '2абатр'), (6, '3абатр')], default=1, verbose_name='Батерея')),
                ('coordinates', models.CharField(max_length=30, unique=True, verbose_name='Координати')),
                ('left_dgress', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Кут вліво')),
                ('right_dgress', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Кут вправо')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Вогнева позиція',
                'verbose_name_plural': 'Вогневі позиції',
            },
        ),
        migrations.CreateModel(
            name='Powders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Заряд',
                'verbose_name_plural': 'Заряди',
            },
        ),
        migrations.CreateModel(
            name='Shells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
                ('color', colorfield.fields.ColorField(default='6eae00', image_field=None, max_length=25, samples=None, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Снаряд',
                'verbose_name_plural': 'Снаряди',
            },
        ),
    ]
