# Generated by Django 5.1 on 2024-11-01 11:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firework', '0005_alter_shells_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powders',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='shells',
            name='color',
            field=colorfield.fields.ColorField(default='33b918', image_field=None, max_length=25, samples=None, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='shells',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Назва'),
        ),
    ]
