# Generated by Django 5.1 on 2024-11-01 11:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firework', '0006_alter_powders_name_alter_shells_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shells',
            name='color',
            field=colorfield.fields.ColorField(default='328bb6', image_field=None, max_length=25, samples=None, verbose_name='Колір'),
        ),
    ]
