# Generated by Django 5.1 on 2024-11-01 11:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firework', '0007_alter_shells_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablesFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell', models.CharField(choices=[('M107', 'M107'), ('M864', 'M864'), ('M483', 'M483'), ('F2', 'F2'), ('LU 211', 'LU 211'), ('F5', 'F5'), ('MKM(Ofd)', 'MKM(Ofd)'), ('HE ER FBBB', 'HE ER FBBB'), ('HE ER FBBT', 'HE ER FBBT'), ('M77', 'M77'), ('M795', 'M795'), ('OE F3 (56/69)', 'OE F3 (56/69)'), ('M741', 'M741'), ('М9603', 'М9603'), ('M982', 'M982'), ('М549А1', 'М549А1'), ('ERO2A1', 'ERO2A1'), ('ERO2A1 BB', 'ERO2A1 BB'), ('DM121', 'DM121'), ('KTA', 'KTA'), ('L15(A1/A2)', 'L15(A1/A2)')], default=1, max_length=50, verbose_name='Снаряд')),
                ('powder', models.CharField(choices=[('M119(А1/A2)', 'M119(А1/A2)'), ('M3A1', 'M3A1'), ('М4(А1/A2)', 'М4(А1/A2)'), ('F1', 'F1'), ('BB HB', 'BB HB'), ('DM72', 'DM72'), ('TC-F', 'TC-F'), ('TCME(100)', 'TCME(100)'), ('TCMSIL', 'TCMSIL'), ('TCM-C', 'TCM-C'), ('М231', 'М231'), ('М232', 'М232'), ('М64A1', 'М64A1'), ('М92', 'М92'), ('M203', 'M203'), ('NR13C1', 'NR13C1'), ('L10-A1', 'L10-A1'), ('CH8', 'CH8'), ('KTA5928', 'KTA5928'), ('KTA5933', 'KTA5933')], default=1, max_length=50, verbose_name='Заряд')),
                ('number_powder', models.CharField(choices=[('Повний', 'Повний'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='Повний', max_length=50, verbose_name='Номер заряду')),
                ('additional_powder', models.CharField(choices=[('M119(А1/A2)', 'M119(А1/A2)'), ('M3A1', 'M3A1'), ('М4(А1/A2)', 'М4(А1/A2)'), ('F1', 'F1'), ('BB HB', 'BB HB'), ('DM72', 'DM72'), ('TC-F', 'TC-F'), ('TCME(100)', 'TCME(100)'), ('TCMSIL', 'TCMSIL'), ('TCM-C', 'TCM-C'), ('М231', 'М231'), ('М232', 'М232'), ('М64A1', 'М64A1'), ('М92', 'М92'), ('M203', 'M203'), ('NR13C1', 'NR13C1'), ('L10-A1', 'L10-A1'), ('CH8', 'CH8'), ('KTA5928', 'KTA5928'), ('KTA5933', 'KTA5933')], max_length=50, verbose_name='Додатковий заряд')),
                ('min_distance', models.FloatField(verbose_name='Мінімальна відстань для розрахунків')),
                ('max_distance', models.FloatField(verbose_name='Максимальна відстань для розрахунків')),
                ('arc_shell', models.BooleanField(default=False, verbose_name='АРС')),
            ],
        ),
        migrations.AlterField(
            model_name='shells',
            name='color',
            field=colorfield.fields.ColorField(default='abbcc4', image_field=None, max_length=25, samples=None, verbose_name='Колір'),
        ),
    ]
