# Generated by Django 5.1 on 2024-11-01 11:44

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firework', '0009_alter_shells_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shells',
            name='color',
            field=colorfield.fields.ColorField(default='bc3c63', image_field=None, max_length=25, samples=None, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='tablesfire',
            name='additional_powder',
            field=models.CharField(blank=True, choices=[('M119(А1/A2)', 'M119(А1/A2)'), ('M3A1', 'M3A1'), ('М4(А1/A2)', 'М4(А1/A2)'), ('F1', 'F1'), ('BB HB', 'BB HB'), ('DM72', 'DM72'), ('TC-F', 'TC-F'), ('TCME(100)', 'TCME(100)'), ('TCMSIL', 'TCMSIL'), ('TCM-C', 'TCM-C'), ('М231', 'М231'), ('М232', 'М232'), ('М64A1', 'М64A1'), ('М92', 'М92'), ('M203', 'M203'), ('NR13C1', 'NR13C1'), ('L10-A1', 'L10-A1'), ('CH8', 'CH8'), ('KTA5928', 'KTA5928'), ('KTA5933', 'KTA5933')], max_length=50, verbose_name='Додатковий заряд'),
        ),
    ]
